### PR TITLE
fixes problem of setPhoneNumber

### PR DESCRIPTION
**Pull request by SubhamTyagi**
@ialokim this PR fixes the problem when any one set the phone number by calling setPhoneNumber().
i have find that[ isValid() ](https://github.com/SubhamTyagi/android-phone-field/blob/d73ec9d76a8cc1f7cc67f3280e68a55a19af653b/phone-field/src/main/java/com/github/ialokim/phonefield/PhoneField.java#L289) creating the problem while pasting the number .

### CODE REVIEW

**Comment by ialokim** [comment]
> the problem while we call setPhoneNumber(String rawNumber)

What is exactly not working with the current implementation? Could you provide an example where it is failing currently?

Regarding the validation when pasting numbers, I'm going to look into this.

**Comment by ialokim** [comment]
Okay, I've added some logic for better paste handling with [f3c6ba](../commit/f3c6ba935a4f2bdbb348571d4ecd98e25d36bd8f). Can you check if this is working for you with release 0.2.2?

I'm going to close this PR.

**Comment by ialokim** [comment]
Please check out 0.2.3, there was an error building it on jitpack.

**Comment by ialokim** [comment]
@SubhamTyagi, did you update your dependency to 0.2.3? Is it working for you now?

**Comment by SubhamTyagi** [comment]
[yes](https://github.com/SubhamTyagi/openinwa/blob/e8c6a1b6db9bec89a9fc6a897df3d16cd377ffcc/app/build.gradle#L30),  it is working well.

**Comment by ialokim** [comment]
Glad to hear!

**Pull request closed without merging**
